import { default as domainData } from './domain_changelog.js';

// Attribute lists per topic (matching standards/audits.json)
export const botabilityDataVariables = [
    'crawlable', 'text-content', 'schema-government-organization',
    'status', 'xml', 'valid', 'allowed', 'sitemap-robots',
    'canonical', 'link-text', 'hreflang'
]

export const accessibilityDataVariables = [
    'accesskeys', 'aria-allowed-attr', 'aria-allowed-role', 'aria-command-name',
    'aria-conditional-attr', 'aria-deprecated-role', 'aria-dialog-name',
    'aria-hidden-body', 'aria-hidden-focus', 'aria-input-field-name',
    'aria-meter-name', 'aria-progressbar-name', 'aria-prohibited-attr',
    'aria-required-attr', 'aria-required-children', 'aria-required-parent',
    'aria-roles', 'aria-text', 'aria-toggle-field-name', 'aria-tooltip-name',
    'aria-treeitem-name', 'aria-valid-attr-value', 'aria-valid-attr',
    'button-name', 'bypass', 'color-contrast', 'definition-list', 'dlitem',
    'document-title', 'duplicate-id-aria', 'form-field-multiple-labels',
    'frame-title', 'heading-order', 'html-has-lang', 'html-lang-valid',
    'html-xml-lang-mismatch', 'image-alt', 'image-redundant-alt',
    'input-button-name', 'input-image-alt', 'label', 'link-in-text-block',
    'link-name', 'list', 'listitem', 'meta-refresh', 'meta-viewport',
    'object-alt', 'select-name', 'skip-link', 'tabindex',
    'table-duplicate-name', 'target-size', 'td-headers-attr',
    'th-has-data-cells', 'valid-lang', 'video-caption', 'empty-heading',
    'identical-links-same-purpose', 'landmark-one-main',
    'label-content-name-mismatch', 'table-fake-caption', 'td-has-header',
    'image-aspect-ratio', 'doctype', 'charset'
]

export const usabilityDataVariables = [
    'title', 'description', 'readability', 'viewport', 'www',
    'cls', 'fcp', 'inp', 'lcp', 'ttfb',
    'ogsitename', 'ogtype', 'ogtitle', 'ogdescription',
    'ogurl', 'ogimage', 'ogimagealt'
]

export const securityDataVariables = [
    'csp', 'hsts', 'securitytxt', 'xcontenttypeoptions',
    'errors-in-console', 'clickjacking-mitigation',
    'paste-preventing-inputs', 'https', 'dotgov'
]

// Map each attribute to its topic
export const variablesMap = new Map([
    ...botabilityDataVariables.map(v => [v, 'botability']),
    ...accessibilityDataVariables.map(v => [v, 'accessibility']),
    ...usabilityDataVariables.map(v => [v, 'usability']),
    ...securityDataVariables.map(v => [v, 'security']),
]);

// Map topics to their attribute lists
export const variableTopics = new Map([
    ['botability', botabilityDataVariables],
    ['accessibility', accessibilityDataVariables],
    ['usability', usabilityDataVariables],
    ['security', securityDataVariables],
]);

export const stateDomainList = [
    'alabama.gov',
    'alaska.gov',
    'az.gov',
    'arkansas.gov',
    'ca.gov',
    'colorado.gov',
    'ct.gov',
    'de.gov',
    'myflorida.gov',
    'georgia.gov',
    'hawaii.gov',
    'idaho.gov',
    'illinois.gov',
    'in.gov',
    'iowa.gov',
    'kansas.gov',
    'kentucky.gov',
    'louisiana.gov',
    'maine.gov',
    'maryland.gov',
    'mass.gov',
    'michigan.gov',
    'mn.gov',
    'mississippi.gov',
    'mo.gov',
    'mt.gov',
    'nebraska.gov',
    'nv.gov',
    'nh.gov',
    'nj.gov',
    'nm.gov',
    'ny.gov',
    'nc.gov',
    'nd.gov',
    'ohio.gov',
    'oklahoma.gov',
    'oregon.gov',
    'pa.gov',
    'ri.gov',
    'sc.gov',
    'sd.gov',
    'tn.gov',
    'texas.gov',
    'utah.gov',
    'vermont.gov',
    'virginia.gov',
    'wa.gov',
    'wv.gov',
    'wisconsin.gov',
    'wyo.gov',
    'dc.gov',
]

export const cityDomainList = [
    'abilenetx.gov',
    'akronohio.gov',
    'albanyny.gov',
    'cabq.gov',
    'alexandriava.gov',
    'allentownpa.gov',
    'allentx.gov',
    'amarillo.gov',
    'anaheim.net',
    'annapolis.gov',
    'antiochca.gov',
    'arlingtontx.gov',
    'arvadaco.gov',
    'atlantaga.gov',
    'augustaga.gov',
    'augustamaine.gov',
    'austintexas.gov',
    'bakersfieldcity.us',
    'beaumonttexas.gov',
    'bellevuewa.gov',
    'bendoregon.gov',
    'berkeleyca.gov',
    'billingsmt.gov',
    'billingsmtpublicworks.gov',
    'birminghamal.gov',
    'bismarcknd.gov',
    'cityofboise.org',
    'boston.gov',
    'bouldercolorado.gov',
    'bridgeportct.gov',
    'brla.gov',
    'brockton.ma.us',
    'brokenarrowok.gov',
    'brownsvilletx.gov',
    'buckeyeaz.gov',
    'buffalony.gov',
    'bunkerhilltx.gov',
    'burbankca.gov',
    'cambridgema.gov',
    'capecoral.gov',
    'capecoral.gov',
    'carlsbadca.gov',
    'carmelindiana.gov',
    'cityofcarrollton.com',
    'chandleraz.gov',
    'chandlerazpd.gov',
    'charleston-sc.gov',
    'charlestonwv.gov',
    'charlottenc.gov',
    'chattanooga.gov',
    'cityofchesapeake.net',
    'chicoca.gov',
    'chulavistaca.gov',
    'cincinnati-oh.gov',
    'cityofconroe.org',
    'hayward-ca.gov',
    'cityofirvine.org',
    'cityoflancasterca.org',
    'ci.lubbock.tx.us',
    'cityofmobile.gov',
    'cityofnormandy.gov',
    'cityofpalmdaleca.gov',
    'phoenix.gov',
    'cityofsacramento.gov',
    'cityofsanmateo.org',
    'cityoftulsa.org',
    'cityofvacaville.gov',
    'clarksvilletn.gov',
    'clevelandohio.gov',
    'cityofclovis.com',
    'coloradosprings.gov',
    'columbiasc.gov',
    'columbus.gov',
    'como.gov',
    'concordnc.gov',
    'concordnh.gov',
    'coralsprings.gov',
    'cor.net',
    'coronaca.gov',
    'corpuschristitx.gov',
    'costamesaca.gov',
    'cstx.gov',
    'dallas.gov',
    'daytonohio.gov',
    'dearborn.gov',
    'cityofdenton.com',
    'detroitmi.gov',
    'detroitmi.gov',
    'durhamnc.gov',
    'eastgrmi.gov',
    'elcajon.gov',
    'elginil.gov',
    'elkgrovecity.org',
    'elmonteca.gov',
    'escondido.gov',
    'everettwa.gov',
    'fargond.gov',
    'fayetteville-ar.gov',
    'fayettevillenc.gov',
    'seattle.gov',
    'surpriseaz.gov',
    'fishersin.gov',
    'flpd.gov',
    'fontanaca.gov',
    'fcgov.com',
    'fortworthtexas.gov',
    'fremont.gov',
    'fremontpolice.gov',
    'fresno.gov',
    'friscotexas.gov',
    'cityoffullerton.com',
    'gainesvillefl.gov',
    'ggcity.org',
    'garlandtx.gov',
    'glendaleaz.gov',
    'glendaleca.gov',
    'goodyearaz.gov',
    'grandrapidsmi.gov',
    'greeleygov.com',
    'greenbaywi.gov',
    'greensboro-nc.gov',
    'greshamoregon.gov',
    'hampton.gov',
    'harrisburgpa.gov',
    'helenamt.gov',
    'cityofhenderson.com',
    'hialeahfl.gov',
    'highpointnc.gov',
    'hillsboro-oregon.gov',
    'houstontx.gov',
    'huntingtonbeachca.gov',
    'huntsvilleal.gov',
    'independencemo.gov',
    'indianhill.gov',
    'indy.gov',
    'irvingtx.gov',
    'jacksonms.gov',
    'jacksonville.gov',
    'jcmo.gov',
    'jeffersoncitymo.gov',
    'jerseycitynj.gov',
    'joliet.gov',
    'kannapolisnc.gov',
    'kcmo.gov',
    'kentwa.gov',
    'killeentexas.gov',
    'knoxvilletn.gov',
    'knoxvilletnpolice.gov',
    'lacity.gov',
    'lakewood.org',
    'lansingmi.gov',
    'cityoflaredo.com',
    'lascruces.gov',
    'lasvegasnevada.gov',
    'leaguecitytx.gov',
    'longbeach.gov',
    'louisvilleky.gov',
    'lowellma.gov',
    'lynnma.gov',
    'cityofmadison.com',
    'manchesternh.gov',
    'memphistn.gov',
    'mesquitetx.gov',
    'miamigardens-fl.gov',
    'miami.gov',
    'midlandtexas.gov',
    'milwaukee.gov',
    'minneapolismn.gov',
    'miramarfl.gov',
    'miramarfl.gov',
    'modestogov.com',
    'montgomeryal.gov',
    'moval.gov',
    'murfreesborotn.gov',
    'murrietaca.gov',
    'cityofnampa.us',
    'newarknj.gov',
    'newbedford-ma.gov',
    'newbraunfels.gov',
    'newhavenct.gov',
    'nnva.gov',
    'nola.gov',
    'norfolk.gov',
    'normanok.gov',
    'northcharleston.org',
    'oaklandca.gov',
    'odessa-tx.gov',
    'olatheks.gov',
    'olympiawa.gov',
    'ontarioca.gov',
    'cityoforange.org',
    'orlando.gov',
    'opkansas.org',
    'palmbayflorida.org',
    'pasadena.gov',
    'pasadenatx.gov',
    'patersonnj.gov',
    'pearlandtx.gov',
    'peoriaaz.gov',
    'peoriagov.org',
    'piedmont.ca.gov',
    'pittsburghpa.gov',
    'plano.gov',
    'pomonaca.gov',
    'pompanobeachfl.gov',
    'portland.gov',
    'providenceri.gov',
    'quincyma.gov',
    'raleighnc.gov',
    'cityofrc.us',
    'reno.gov',
    'rentonwa.gov',
    'rialtoca.gov',
    'richmondca.gov',
    'rochestermn.gov',
    'rockfordil.gov',
    'roundrocktexas.gov',
    'rrnm.gov',
    'rva.gov',
    'sa.gov',
    'salemor.gov',
    'cityofsalinas.org',
    'sanbernardino.gov',
    'sandiego.gov',
    'sandyspringsga.gov',
    'sanjoseca.gov',
    'santa-ana.org',
    'santaclaraca.gov',
    'santaclarita.gov',
    'santafenm.gov',
    'srcity.org',
    'savannahga.gov',
    'scottsdaleaz.gov',
    'sgcityutah.gov',
    'shreveportla.gov',
    'simivalley.gov',
    'siouxfalls.gov',
    'southbendin.gov',
    'southsideplacetx.gov',
    'sparksnv.gov',
    'spokane.gov',
    'spokanevalleywa.gov',
    'springfield-ma.gov',
    'springfieldmo.gov',
    'stamfordct.gov',
    'sterlingheights.gov',
    'stgeorgela.gov',
    'stlouis-mo.gov',
    'stocktonca.gov',
    'stpaul.gov',
    'sugarlandtx.gov',
    'syr.gov',
    'tacoma.gov',
    'tampa.gov',
    'temeculaca.gov',
    'tempe.gov',
    'thorntonco.gov',
    'toaks.gov',
    'toledo.oh.gov',
    'topeka.org',
    'tucsonaz.gov',
    'tuscaloosa-al.gov',
    'tylertexas.gov',
    'vallejo.gov',
    'cityofvancouver.us',
    'victorvilleca.gov',
    'virginiabeach.gov',
    'visalia.gov',
    'waco-texas.com',
    'walkermi.gov',
    'warrenmi.gov',
    'wichitafallstx.gov',
    'wichita.gov',
    'wilmingtonnc.gov',
    'worcesterma.gov',
    'yonkersny.gov',
    'yumaaz.gov',
    'chicago.gov',
    'cityofsouthfultonga.gov',
    'eugene-or.gov',
    'harriscountytx.gov',
    'baytown.org',
    'deerparktx.gov',
    'ci.friendswood.tx.us',
    'laportetx.gov',
    'missouricitytx.gov',
    'wallertexas.gov',
    'cityofwebster.com',
    'westutx.gov',
    'taylorlakevillage.us',
    'staffordtx.gov',
    'springvalleytx.com',
    'shoreacrestx.us',
    'southhoustontx.gov',
    'seabrooktx.gov',
    'cityofpineypoint.com',
    'cityofkaty.com',
    'nassaubay.com',
    'morganspoint-tx.com',
    'jerseyvillagetx.com',
    'jacintocity-tx.gov',
    'hilshirevillagetexas.com',
    'cityofhunterscreek.com',
    'thecityofhedwigvillage.com',
    'cityofgalenapark-tx.gov',
    'ellago-tx.gov',
    'cityofhumbletx.gov',
    'bellairetx.gov',
];

const domains = domainData();

export const countyDomainList = domains.filter(d => d.name.includes('County') || d.name.includes('Parish')).map(d => d.url);

export const eduDomainList = domains.filter(d => d.url.endsWith('edu')).map(d => d.url);

export const addRankingPosition = function(data, attribute) {
    if (!data || data.length === 0) return data;
    let currentScore = 100;
    let rankingPosition = 1;
    if (attribute) {
        currentScore = data[0].scores[attribute].score;
    } else {
        currentScore = data[0].overallScore;
    }
    data.forEach(o => {
        let rankingScore = null;
        if (attribute) {
            rankingScore = o.scores[attribute].score;
        } else {
            rankingScore = o.overallScore;
        }
        if (rankingScore != currentScore) {
            currentScore = rankingScore;
            rankingPosition = rankingPosition + 1;
        }
        o.rankingPosition = rankingPosition;
    })

    return data;
}
